'''
### set creation data

# nomenclature 

attributes: everything that composes a character (attrkey: attrvalue)
    attrkeys: rarity, gender, costume, hat, hair, glasses, eyes, nose, 
            beard, bowtie, jacket, torso, legs, shoes, skin
    attrvalues: gray/green/blue...(rarity), male/female (gender), none/style01/style02...(slots)

style attributes: influence the visual and rarity of the character (slot: style)
    slots: costume, hat, hair, glasses, eyes, nose, beard, bowtie, jacket, torso, legs, shoes, skin
    styles: none, style01, style02...

drops: (style, dropchance) pairs
                                            
display value: translation from (attrkey, attrvalue) to display string
    eg: (rarity, blue): Rare
        (gender, male): Male
        (costume, style01): Polygon Astronaut Costume
'''        

drop_proportion = {
    'gray': 8,
    'green': 5,
    'blue': 3,
    'purple': 2,
    'orange': 1,
    'iridescent': 1
}

drop_points = {
    'gray': 3,
    'green': 4,
    'blue': 5,
    'purple': 7,
    'orange': 9,
    'iridescent': 999
}

# drops reference data
boy_drops_ref = {
    'costume':  [('none',                   9880),
                 ('style01',                'iridescent'),
                 ('style02',                'iridescent'), 
                 ('style03',                'iridescent'), 
                 ('style04',                'iridescent'), 
                 ('style05',                'iridescent'), 
                 ('style06',                'iridescent'), 
                 ('style07',                'iridescent'), 
                 ('style08',                'iridescent'), 
                 ('style09',                'iridescent'), 
                 ('style10',                'iridescent'), 
                 ('style11',                'iridescent'), 
                 ('style12',                'iridescent'), 
                 ('style13',                'iridescent'), 
                 ('style14',                'iridescent'), 
                 ('style15',                'iridescent'), 
                 ('style16',                'iridescent'),
                 ('style17',                'iridescent'),
                 ('style18',                'iridescent'),
                 ('style19',                'iridescent'),
                 ('style20',                'iridescent'),
                 ('style21',                'iridescent'),
                 ('style22',                'iridescent'),
                 ('style23',                'iridescent'),
                 ('style24',                'iridescent'),
                 ('style25',                'iridescent'),
                 ('style26',                'iridescent'),
                 ('style27',                'iridescent'),
                 ('style28',                'iridescent'),
                 ('style29',                'iridescent'),
                 ('style30',                'iridescent')],
    'hat':      [('none',                   7500), 
                 ('style01',                'blue'), 
                 ('style02',                'purple'), 
                 ('style03',                'purple'), 
                 ('style04',                'purple'), 
                 ('style05',                'orange'), 
                 ('style06',                'blue'), 
                 ('style07',                'blue'), 
                 ('style08',                'blue'), 
                 ('style09',                'blue'), 
                 ('style10',                'orange'), 
                 ('style11',                'orange'), 
                 ('style12',                'purple'), 
                 ('style13',                'orange'), 
                 ('style14',                'blue'), 
                 ('style15',                'blue'), 
                 ('style16',                'purple'), 
                 ('style17',                'purple'), 
                 ('style18',                'blue'), 
                 ('style19',                'blue'), 
                 ('style20',                'blue'), 
                 ('style21',                'blue'), 
                 ('style22',                'blue'), 
                 ('style23',                'blue'), 
                 ('style24',                'blue'), 
                 ('style25',                'blue'), 
                 ('style26',                'blue'), 
                 ('style27',                'blue'), 
                 ('style28',                'blue'),
                 ('style29',                'blue'),
                 ('style30',                'blue'),
                 ('style31',                'blue'),
                 ('style32',                'blue')],
    'hair':     [('none',                   0),
                 ('style01_blond',          'blue'),
                 ('style01_brown',          'gray'),
                 ('style01_dark-gray',      'gray'),
                 ('style01_light-gray',     'green'),
                 ('style01_pink',           'orange'),
                 ('style01_red',            'purple'),
                 ('style02_blond',          'blue'),
                 ('style02_brown',          'gray'),
                 ('style02_dark-gray',      'gray'),
                 ('style02_light-gray',     'green'),
                 ('style02_pink',           'orange'),
                 ('style02_red',            'purple'),
                 ('style03_blond',          'blue'),
                 ('style03_brown',          'gray'),
                 ('style03_dark-gray',      'gray'),
                 ('style03_light-gray',     'green'),
                 ('style03_pink',           'orange'),
                 ('style03_red',            'purple'),
                 ('style04_blond',          'blue'),
                 ('style04_brown',          'gray'),
                 ('style04_dark-gray',      'gray'),
                 ('style04_light-gray',     'green'),
                 ('style04_pink',           'orange'),
                 ('style04_red',            'purple'),
                 ('style05_blond',          'blue'),
                 ('style05_brown',          'gray'),
                 ('style05_dark-gray',      'gray'),
                 ('style05_light-gray',     'green'),
                 ('style05_pink',           'orange'),
                 ('style05_red',            'purple'),
                 ('style06_blond',          'blue'),
                 ('style06_brown',          'gray'),
                 ('style06_dark-gray',      'gray'),
                 ('style06_light-gray',     'green'),
                 ('style06_pink',           'orange'),
                 ('style06_red',            'purple'),
                 ('style07_blond',          'blue'),
                 ('style07_brown',          'gray'),
                 ('style07_dark-gray',      'gray'),
                 ('style07_light-gray',     'green'),
                 ('style07_pink',           'orange'),
                 ('style07_red',            'purple'),
                 ('style08_blond',          'blue'),
                 ('style08_brown',          'gray'),
                 ('style08_dark-gray',      'gray'),
                 ('style08_light-gray',     'green'),
                 ('style08_pink',           'orange'),
                 ('style08_red',            'purple'),
                 ('style09_blond',          'blue'),
                 ('style09_brown',          'gray'),
                 ('style09_dark-gray',      'gray'),
                 ('style09_light-gray',     'green'),
                 ('style09_pink',           'orange'),
                 ('style09_red',            'purple')],
    'glasses':  [('none',                   4000),                 
                 ('style01',                'blue'), 
                 ('style02',                'green'), 
                 ('style03',                'blue'), 
                 ('style04',                'purple'), 
                 ('style05',                'purple'), 
                 ('style06',                'blue'), 
                 ('style07',                'green'), 
                 ('style08',                'purple'), 
                 ('style09',                'blue'), 
                 ('style10',                'green'), 
                 ('style11',                'blue'), 
                 ('style12',                'blue'), 
                 ('style13',                'orange'), 
                 ('style14',                'green'), 
                 ('style15',                'purple')], 
    'eyes':     [('none',                   0),
                 ('style01',                'purple'), 
                 ('style02',                'orange'), 
                 ('style03',                'blue'), 
                 ('style04',                'blue'), 
                 ('style05',                'gray')], 
    'nose':     [('none',                   0),
                 ('style01',                'gray'), 
                 ('style02',                'green'), 
                 ('style03',                'blue')],
    'beard':    [('none',                   3000),
                 ('style01_blond',          'blue'),
                 ('style01_brown',          'green'),
                 ('style01_dark-gray',      'green'),
                 ('style01_light-gray',     'green'),
                 ('style01_pink',           'orange'),
                 ('style01_red',            'purple'),
                 ('style02_blond',          'blue'),
                 ('style02_brown',          'green'),
                 ('style02_dark-gray',      'green'),
                 ('style02_light-gray',     'green'),
                 ('style02_pink',           'orange'),
                 ('style02_red',            'purple'),
                 ('style03_blond',          'blue'),
                 ('style03_brown',          'green'),
                 ('style03_dark-gray',      'green'),
                 ('style03_light-gray',     'green'),
                 ('style03_pink',           'orange'),
                 ('style03_red',            'purple'),
                 ('style04_blond',          'blue'),
                 ('style04_brown',          'green'),
                 ('style04_dark-gray',      'green'),
                 ('style04_light-gray',     'green'),
                 ('style04_pink',           'orange'),
                 ('style04_red',            'purple'),
                 ('style05_blond',          'blue'),
                 ('style05_brown',          'green'),
                 ('style05_dark-gray',      'green'),
                 ('style05_light-gray',     'green'),
                 ('style05_pink',           'orange'),
                 ('style05_red',            'purple'),
                 ('style06_blond',          'blue'),
                 ('style06_brown',          'green'),
                 ('style06_dark-gray',      'green'),
                 ('style06_light-gray',     'green'),
                 ('style06_pink',           'orange'),
                 ('style06_red',            'purple'),
                 ('style07_blond',          'blue'),
                 ('style07_brown',          'green'),
                 ('style07_dark-gray',      'green'),
                 ('style07_light-gray',     'green'),
                 ('style07_pink',           'orange'),
                 ('style07_red',            'purple'),
                 ('style08_blond',          'blue'),
                 ('style08_brown',          'green'),
                 ('style08_dark-gray',      'green'),
                 ('style08_light-gray',     'green'),
                 ('style08_pink',           'orange'),
                 ('style08_red',            'purple'),
                 ('style09_blond',          'blue'),
                 ('style09_brown',          'green'),
                 ('style09_dark-gray',      'green'),
                 ('style09_light-gray',     'green'),
                 ('style09_pink',           'orange'),
                 ('style09_red',            'purple'),
                 ('style10_blond',          'blue'),
                 ('style10_brown',          'green'),
                 ('style10_dark-gray',      'green'),
                 ('style10_light-gray',     'green'),
                 ('style10_pink',           'orange'),
                 ('style10_red',            'purple'),
                 ('style11',                'green')],
    'bowtie':   [('none',                   9000), 
                 ('style01',                'purple'), 
                 ('style02',                'purple'), 
                 ('style03',                'purple'), 
                 ('style04',                'purple')], 
    'jacket':   [('none',                   8000), 
                 ('style01',                'blue'), 
                 ('style02',                'blue'), 
                 ('style03',                'blue'), 
                 ('style04',                'orange'), 
                 ('style05',                'blue'), 
                 ('style06',                'blue'), 
                 ('style07',                'blue')], 
    'torso':    [('none',                   0),
                 ('style01',                'blue'), 
                 ('style02',                'purple'), 
                 ('style03',                'orange'), 
                 ('style04',                'blue'), 
                 ('style05',                'green'), 
                 ('style06',                'green'), 
                 ('style07',                'green'), 
                 ('style08',                'green'), 
                 ('style09',                'green'), 
                 ('style10',                'gray'), 
                 ('style11',                'blue'), 
                 ('style12',                'green'), 
                 ('style13',                'green'), 
                 ('style14',                'green'), 
                 ('style15',                'green'), 
                 ('style16',                'blue'), 
                 ('style17',                'gray'), 
                 ('style18',                'gray'), 
                 ('style19',                'gray'), 
                 ('style20',                'gray'), 
                 ('style21',                'purple'), 
                 ('style22',                'purple'), 
                 ('style23',                'gray'), 
                 ('style24',                'purple'), 
                 ('style25',                'blue'), 
                 ('style26',                'blue'), 
                 ('style27',                'blue'), 
                 ('style28',                'gray'),
                 ('style29',                'purple'), 
                 ('style30',                'gray'), 
                 ('style31',                'blue'), 
                 ('style32',                'blue'), 
                 ('style33',                'gray'), 
                 ('style34',                'purple'), 
                 ('style35',                'purple'), 
                 ('style36',                'purple'), 
                 ('style37',                'green'), 
                 ('style38',                'blue'), 
                 ('style39',                'blue'), 
                 ('style40',                'orange'), 
                 ('style41',                'gray'), 
                 ('style42',                'gray'), 
                 ('style43',                'purple'), 
                 ('style44',                'purple'), 
                 ('style45',                'blue')], 
    'legs':     [('none',                   0),
                 ('style01',                'green'), 
                 ('style02',                'purple'), 
                 ('style03',                'green'), 
                 ('style04',                'gray'), 
                 ('style05',                'gray'), 
                 ('style06',                'gray'), 
                 ('style07',                'blue'), 
                 ('style08',                'green'), 
                 ('style09',                'blue'), 
                 ('style10',                'orange'), 
                 ('style11',                'purple'), 
                 ('style12',                'gray'), 
                 ('style13',                'green'), 
                 ('style14',                'green'), 
                 ('style15',                'gray'), 
                 ('style16',                'gray'), 
                 ('style17',                'blue'), 
                 ('style18',                'green'), 
                 ('style19',                'blue'), 
                 ('style20',                'orange'), 
                 ('style21',                'purple')], 
    'shoes':    [('none',                   0),
                 ('style01',                'purple'), 
                 ('style02',                'blue'), 
                 ('style03',                'blue'), 
                 ('style04',                'green'), 
                 ('style05',                'orange'), 
                 ('style06',                'gray'), 
                 ('style07',                'gray'), 
                 ('style08',                'blue'), 
                 ('style09',                'gray'), 
                 ('style10',                'blue'), 
                 ('style11',                'orange'), 
                 ('style12',                'purple'), 
                 ('style13',                'green'), 
                 ('style14',                'green'), 
                 ('style15',                'gray'), 
                 ('style16',                'gray'), 
                 ('style17',                'green'), 
                 ('style18',                'green'), 
                 ('style19',                'blue'), 
                 ('style20',                'green'), 
                 ('style21',                'purple')],
    'skin':     [('none',                   0),
                 ('style01',                'blue'), 
                 ('style02',                'orange'), 
                 ('style03',                'purple'), 
                 ('style04',                'gray'), 
                 ('style05',                'gray'),
                 ('style06',                'gray')]
}

girl_drops_ref = {
    'costume':  [('none',                   9880),
                 ('style01',                'iridescent'),
                 ('style02',                'iridescent'), 
                 ('style03',                'iridescent'), 
                 ('style04',                'iridescent'), 
                 ('style05',                'iridescent'), 
                 ('style06',                'iridescent'), 
                 ('style07',                'iridescent'), 
                 ('style08',                'iridescent'), 
                 ('style09',                'iridescent'), 
                 ('style10',                'iridescent'), 
                 ('style11',                'iridescent'), 
                 ('style12',                'iridescent'), 
                 ('style13',                'iridescent'), 
                 ('style14',                'iridescent'), 
                 ('style15',                'iridescent'), 
                 ('style16',                'iridescent'), 
                 ('style17',                'iridescent'), 
                 ('style18',                'iridescent'), 
                 ('style19',                'iridescent'), 
                 ('style20',                'iridescent'),
                 ('style21',                'iridescent'),
                 ('style22',                'iridescent'),
                 ('style23',                'iridescent'),
                 ('style24',                'iridescent'),
                 ('style25',                'iridescent'),
                 ('style26',                'iridescent'),
                 ('style27',                'iridescent'),
                 ('style28',                'iridescent'),
                 ('style29',                'iridescent'),
                 ('style30',                'iridescent')],
    'hat':      [('none',                   7500), 
                 ('style01',                'blue'), 
                 ('style02',                'purple'), 
                 ('style03',                'purple'), 
                 ('style04',                'purple'), 
                 ('style05',                'orange'), 
                 ('style06',                'purple'), 
                 ('style07',                'blue'), 
                 ('style08',                'blue'), 
                 ('style09',                'blue'), 
                 ('style10',                'orange'), 
                 ('style11',                'orange'), 
                 ('style12',                'purple'), 
                 ('style13',                'orange'), 
                 ('style14',                'blue'), 
                 ('style15',                'blue'), 
                 ('style16',                'purple'), 
                 ('style17',                'orange'), 
                 ('style18',                'blue'), 
                 ('style19',                'purple'), 
                 ('style20',                'blue'), 
                 ('style21',                'blue'), 
                 ('style22',                'blue'), 
                 ('style23',                'blue'), 
                 ('style24',                'blue'), 
                 ('style25',                'blue'), 
                 ('style26',                'blue'), 
                 ('style27',                'blue'), 
                 ('style28',                'blue'),
                 ('style29',                'blue'),
                 ('style30',                'blue'),
                 ('style31',                'blue'),
                 ('style32',                'blue')],
    'hair':     [('none',                   0),
                 ('style01_blond',          'blue'),
                 ('style01_brown',          'gray'),
                 ('style01_dark-gray',      'gray'),
                 ('style01_light-gray',     'green'),
                 ('style01_pink',           'orange'),
                 ('style01_red',            'purple'),
                 ('style02_blond',          'blue'),
                 ('style02_brown',          'gray'),
                 ('style02_dark-gray',      'gray'),
                 ('style02_light-gray',     'green'),
                 ('style02_pink',           'orange'),
                 ('style02_red',            'purple'),
                 ('style03_blond',          'blue'),
                 ('style03_brown',          'gray'),
                 ('style03_dark-gray',      'gray'),
                 ('style03_light-gray',     'green'),
                 ('style03_pink',           'orange'),
                 ('style03_red',            'purple'),
                 ('style04_blond',          'blue'),
                 ('style04_brown',          'gray'),
                 ('style04_dark-gray',      'gray'),
                 ('style04_light-gray',     'green'),
                 ('style04_pink',           'orange'),
                 ('style04_red',            'purple'),
                 ('style05_blond',          'blue'),
                 ('style05_brown',          'gray'),
                 ('style05_dark-gray',      'gray'),
                 ('style05_light-gray',     'green'),
                 ('style05_pink',           'orange'),
                 ('style05_red',            'purple'),
                 ('style06_blond',          'blue'),
                 ('style06_brown',          'gray'),
                 ('style06_dark-gray',      'gray'),
                 ('style06_light-gray',     'green'),
                 ('style06_pink',           'orange'),
                 ('style06_red',            'purple'),
                 ('style07_blond',          'blue'),
                 ('style07_brown',          'gray'),
                 ('style07_dark-gray',      'gray'),
                 ('style07_light-gray',     'green'),
                 ('style07_pink',           'orange'),
                 ('style07_red',            'purple'),
                 ('style08_blond',          'blue'),
                 ('style08_brown',          'gray'),
                 ('style08_dark-gray',      'gray'),
                 ('style08_light-gray',     'green'),
                 ('style08_pink',           'orange'),
                 ('style08_red',            'purple')],
    'glasses':  [('none',                   4000),
                 ('style01',                'blue'), 
                 ('style02',                'green'), 
                 ('style03',                'blue'), 
                 ('style04',                'purple'), 
                 ('style05',                'purple'), 
                 ('style06',                'blue'), 
                 ('style07',                'green'), 
                 ('style08',                'purple'), 
                 ('style09',                'green'), 
                 ('style10',                'blue'), 
                 ('style11',                'blue'), 
                 ('style12',                'blue'), 
                 ('style13',                'orange'), 
                 ('style14',                'green'), 
                 ('style15',                'purple'),
                 ('style16',                'blue'),
                 ('style17',                'purple'),
                 ('style18',                'blue')], 
    'eyes':     [('none',                   0),
                 ('style01',                'purple'), 
                 ('style02',                'orange'), 
                 ('style03',                'blue'), 
                 ('style04',                'blue'), 
                 ('style05',                'gray')], 
    'nose':     [('none',                   0),
                 ('style01',                'gray'), 
                 ('style02',                'green'), 
                 ('style03',                'blue')], 
    'beard':    [('none',                   10000)], 
    'bowtie':   [('none',                   10000)], 
    'jacket':   [('none',                   7000), 
                 ('style01',                'purple'), 
                 ('style02',                'purple'), 
                 ('style03',                'purple'), 
                 ('style04',                'purple'), 
                 ('style05',                'orange'), 
                 ('style06',                'blue'), 
                 ('style07',                'blue'), 
                 ('style08',                'blue'), 
                 ('style09',                'purple'), 
                 ('style10',                'orange'), 
                 ('style11',                'blue'), 
                 ('style12',                'blue'), 
                 ('style13',                'blue'), 
                 ('style14',                'blue'), 
                 ('style15',                'orange'), 
                 ('style16',                'blue'), 
                 ('style17',                'blue'), 
                 ('style18',                'blue')], 
    'torso':    [('none',                   0),
                 ('style01',                'blue'), 
                 ('style02',                'purple'), 
                 ('style03',                'orange'), 
                 ('style04',                'blue'), 
                 ('style05',                'gray'), 
                 ('style06',                'gray'), 
                 ('style07',                'gray'), 
                 ('style08',                'green'), 
                 ('style09',                'green'), 
                 ('style10',                'gray'), 
                 ('style11',                'blue'), 
                 ('style12',                'green'), 
                 ('style13',                'green'), 
                 ('style14',                'green'), 
                 ('style15',                'green'), 
                 ('style16',                'blue'), 
                 ('style17',                'gray'), 
                 ('style18',                'gray'), 
                 ('style19',                'gray'), 
                 ('style20',                'gray'), 
                 ('style21',                'purple'), 
                 ('style22',                'purple'), 
                 ('style23',                'gray'), 
                 ('style24',                'purple'), 
                 ('style25',                'purple'), 
                 ('style26',                'purple'), 
                 ('style27',                'gray'), 
                 ('style28',                'green'),
                 ('style29',                'blue'), 
                 ('style30',                'blue'), 
                 ('style31',                'orange'), 
                 ('style32',                'purple'), 
                 ('style33',                'green'), 
                 ('style34',                'green'), 
                 ('style35',                'orange'), 
                 ('style36',                'gray'), 
                 ('style37',                'blue'), 
                 ('style38',                'purple'), 
                 ('style39',                'blue'), 
                 ('style40',                'green'), 
                 ('style41',                'blue'), 
                 ('style42',                'orange'), 
                 ('style43',                'purple'), 
                 ('style44',                'green'), 
                 ('style45',                'gray'), 
                 ('style46',                'gray'), 
                 ('style47',                'purple'), 
                 ('style48',                'purple'), 
                 ('style49',                'blue'), 
                 ('style50',                'gray'), 
                 ('style51',                'purple'), 
                 ('style52',                'blue'), 
                 ('style53',                'blue'), 
                 ('style54',                'blue'), 
                 ('style55',                'gray'), 
                 ('style56',                'purple'), 
                 ('style57',                'gray'), 
                 ('style58',                'blue'), 
                 ('style59',                'blue'), 
                 ('style60',                'gray'), 
                 ('style61',                'green'), 
                 ('style62',                'blue'), 
                 ('style63',                'blue'), 
                 ('style64',                'purple')], 
    'legs':     [('none',                   0),
                 ('style01',                'green'), 
                 ('style02',                'purple'), 
                 ('style03',                'green'), 
                 ('style04',                'gray'), 
                 ('style05',                'gray'), 
                 ('style06',                'gray'), 
                 ('style07',                'blue'), 
                 ('style08',                'green'), 
                 ('style09',                'blue'), 
                 ('style10',                'orange'), 
                 ('style11',                'purple'), 
                 ('style12',                'purple'), 
                 ('style13',                'orange'), 
                 ('style14',                'green'), 
                 ('style15',                'blue'), 
                 ('style16',                'green'), 
                 ('style17',                'green'), 
                 ('style18',                'gray'), 
                 ('style19',                'gray'), 
                 ('style20',                'blue'), 
                 ('style21',                'green'),
                 ('style22',                'blue'),
                 ('style23',                'orange'),
                 ('style24',                'purple')], 
    'shoes':    [('none',                   0),
                 ('style01',                'gray'), 
                 ('style02',                'gray'), 
                 ('style03',                'green'), 
                 ('style04',                'green'), 
                 ('style05',                'purple'), 
                 ('style06',                'blue'), 
                 ('style07',                'blue'), 
                 ('style08',                'green'), 
                 ('style09',                'orange'), 
                 ('style10',                'gray'), 
                 ('style11',                'gray'), 
                 ('style12',                'blue'), 
                 ('style13',                'gray'), 
                 ('style14',                'blue'), 
                 ('style15',                'green'), 
                 ('style16',                'purple'), 
                 ('style17',                'purple'), 
                 ('style18',                'green'), 
                 ('style19',                'gray'), 
                 ('style20',                'gray'), 
                 ('style21',                'blue'),
                 ('style22',                'orange'),
                 ('style23',                'orange'),
                 ('style24',                'purple')],
    'skin':     [('none',                   0),
                 ('style01',                'blue'), 
                 ('style02',                'orange'), 
                 ('style03',                'purple'), 
                 ('style04',                'gray'), 
                 ('style05',                'gray'),
                 ('style06',                'gray')]
}

boy_styles_display = {
    'costume':  {'none':                   'none',
                 'style01':                "Polygon Astronaut Costume",
                 'style02':                "Sloth Costume", 
                 'style03':                "Panda Costume", 
                 'style04':                "Polar Bear Costume", 
                 'style05':                "Brown Bear Costume", 
                 'style06':                "Chicken Costume", 
                 'style07':                "Snake Costume", 
                 'style08':                "Gray Cat Costume", 
                 'style09':                "Orange Cat Costume", 
                 'style10':                "Black Cat Costume", 
                 'style11':                "Calico Cat Costume", 
                 'style12':                "Pug Costume", 
                 'style13':                "Monkey Costume", 
                 'style14':                "Crocodile Costume", 
                 'style15':                "Brown Bull Costume", 
                 'style16':                "Black Bull Costume",
                 'style17':                "Alien Costume",
                 'style18':                "Corgi Costume",
                 'style19':                "Owl Costume",
                 'style20':                "Frog Costume",
                 'style21':                "Red Panda Costume", 
                 'style22':                "Cow Costume", 
                 'style23':                "Pit Bull Costume", 
                 'style24':                "Tiger Costume", 
                 'style25':                "Dinosaur Costume", 
                 'style26':                "Penguin Costume",
                 'style27':                "Lion Costume",
                 'style28':                "Pig Costume",
                 'style29':                "Koala Costume",
                 'style30':                "Shark Costume"},
    'hat':      {'none':                   'none', 
                 'style01':                "Blue Conductor's Hat", 
                 'style02':                "Chef's Hat", 
                 'style03':                "Cowboy Hat", 
                 'style04':                "Penguin Hat", 
                 'style05':                "Dog Hat", 
                 'style06':                "Red & White Cap", 
                 'style07':                "Red Stripes Cap", 
                 'style08':                "Red Cap", 
                 'style09':                "Fire Cap", 
                 'style10':                "Duck Cap", 
                 'style11':                "Viking Helmet", 
                 'style12':                "Policeman Cap", 
                 'style13':                "Boat Captain Hat", 
                 'style14':                "Gray Coonskin Hat", 
                 'style15':                "White Coonskin Hat", 
                 'style16':                "Gray Bowler Hat", 
                 'style17':                "Brown Bowler Hat", 
                 'style18':                "Gray Ushanka", 
                 'style19':                "Brown Ushanka", 
                 'style20':                "Green Ushanka", 
                 'style21':                "Green Bandana", 
                 'style22':                "Blue Bandana", 
                 'style23':                "Purple Bandana", 
                 'style24':                "Red Bandana", 
                 'style25':                "Blue Beanie", 
                 'style26':                "Green Beanie", 
                 'style27':                "Yellow Beanie", 
                 'style28':                "Purple Beanie",
                 'style29':                "Red Backwards Cap",
                 'style30':                "Green Backwards Cap",
                 'style31':                "Blue Backwards Cap",
                 'style32':                "Yellow Backwards Cap"},
    'hair':     {'none':                   'none',
                 'style01_blond':          "Blond Short Hair",
                 'style01_brown':          "Brown Short Hair",
                 'style01_dark-gray':      "Dark Gray Short Hair",
                 'style01_light-gray':     "Light Gray Short Hair",
                 'style01_pink':           "Pink Short Hair",
                 'style01_red':            "Red Short Hair",
                 'style02_blond':          "Blond Pompadour Hair",
                 'style02_brown':          "Brown Pompadour Hair",
                 'style02_dark-gray':      "Dark Gray Pompadour Hair",
                 'style02_light-gray':     "Light Gray Pompadour Hair",
                 'style02_pink':           "Pink Pompadour Hair",
                 'style02_red':            "Red Pompadour Hair",
                 'style03_blond':          "Blond Spiky Dreadlocks Hair",
                 'style03_brown':          "Brown Spiky Dreadlocks Hair",
                 'style03_dark-gray':      "Dark Gray Spiky Dreadlocks Hair",
                 'style03_light-gray':     "Light Gray Spiky Dreadlocks Hair",
                 'style03_pink':           "Pink Spiky Dreadlocks Hair",
                 'style03_red':            "Red Spiky Dreadlocks Hair",
                 'style04_blond':          "Blond Emo Swoop Hair",
                 'style04_brown':          "Brown Emo Swoop Hair",
                 'style04_dark-gray':      "Dark Gray Emo Swoop Hair",
                 'style04_light-gray':     "Light Gray Emo Swoop Hair",
                 'style04_pink':           "Pink Emo Swoop Hair",
                 'style04_red':            "Red Emo Swoop Hair",
                 'style05_blond':          "Blond Afro Hair",
                 'style05_brown':          "Brown Afro Hair",
                 'style05_dark-gray':      "Dark Gray Afro Hair",
                 'style05_light-gray':     "Light Gray Afro Hair",
                 'style05_pink':           "Pink Afro Hair",
                 'style05_red':            "Red Afro Hair",
                 'style06_blond':          "Blond Top Knot Hair",
                 'style06_brown':          "Brown Top Knot Hair",
                 'style06_dark-gray':      "Dark Gray Top Knot Hair",
                 'style06_light-gray':     "Light Gray Top Knot Hair",
                 'style06_pink':           "Pink Top Knot Hair",
                 'style06_red':            "Red Top Knot Hair",
                 'style07_blond':          "Blond Mohawk Hair",
                 'style07_brown':          "Brown Mohawk Hair",
                 'style07_dark-gray':      "Dark Gray Mohawk Hair",
                 'style07_light-gray':     "Light Gray Mohawk Hair",
                 'style07_pink':           "Pink Mohawk Hair",
                 'style07_red':            "Red Mohawk Hair",
                 'style08_blond':          "Blond Bald Hair",
                 'style08_brown':          "Brown Bald Hair",
                 'style08_dark-gray':      "Dark Gray Bald Hair",
                 'style08_light-gray':     "Light Gray Bald Hair",
                 'style08_pink':           "Pink Bald Hair",
                 'style08_red':            "Red Bald Hair",
                 'style09_blond':          "Backwards Cap Blond Hair",
                 'style09_brown':          "Backwards Cap Brown Hair",
                 'style09_dark-gray':      "Backwards Cap Dark Gray Hair",
                 'style09_light-gray':     "Backwards Cap Light Gray Hair",
                 'style09_pink':           "Backwards Cap Pink Hair",
                 'style09_red':            "Backwards Cap Red Hair"},
    'glasses':  {'none':                   'none',                 
                 'style01':                "Modern Glasses", 
                 'style02':                "Big Frame Blue Glasses", 
                 'style03':                "Big Frame Green Glasses", 
                 'style04':                "Big Frame Red Glasses", 
                 'style05':                "Yellow Aviator Glasses", 
                 'style06':                "Teal Aviator Glasses", 
                 'style07':                "Gray Aviator Glasses", 
                 'style08':                "Purple Aviator Glasses", 
                 'style09':                "Semi-Rimless Glasses", 
                 'style10':                "Full-Rimmed Glasses", 
                 'style11':                "Small Teashade Sunglasses", 
                 'style12':                "Red Teashade Sunglasses", 
                 'style13':                "Old 3D Glasses", 
                 'style14':                "Black Sunglasses", 
                 'style15':                "Monocle"}, 
    'eyes':     {'none':                   'none',
                 'style01':                "Red Eyes", 
                 'style02':                "Pink Eyes", 
                 'style03':                "Green Eyes", 
                 'style04':                "Blue Eyes", 
                 'style05':                "Black Eyes"}, 
    'nose':     {'none':                   'none',
                 'style01':                "Small Nose", 
                 'style02':                "Medium Nose", 
                 'style03':                "Big Nose"}, 
    
    'beard':    {'none':                   'none',
                 'style01_blond':          "Blond Goatee",
                 'style01_brown':          "Brown Goatee",
                 'style01_dark-gray':      "Dark Gray Goatee",
                 'style01_light-gray':     "Light Gray Goatee",
                 'style01_pink':           "Pink Goatee",
                 'style01_red':            "Red Goatee",
                 'style02_blond':          "Blond Imperial Mustache",
                 'style02_brown':          "Brown Imperial Mustache",
                 'style02_dark-gray':      "Dark Gray Imperial Mustache",
                 'style02_light-gray':     "Light Gray Imperial Mustache",
                 'style02_pink':           "Pink Imperial Mustache",
                 'style02_red':            "Red Imperial Mustache",
                 'style03_blond':          "Blond Walrus Mustache",
                 'style03_brown':          "Brown Walrus Mustache",
                 'style03_dark-gray':      "Dark Gray Walrus Mustache",
                 'style03_light-gray':     "Light Gray Walrus Mustache",
                 'style03_pink':           "Pink Walrus Mustache",
                 'style03_red':            "Red Walrus Mustache",
                 'style04_blond':          "Blond Zappa Moustache",
                 'style04_brown':          "Brown Zappa Moustache",
                 'style04_dark-gray':      "Dark Gray Zappa Moustache",
                 'style04_light-gray':     "Light Gray Zappa Moustache",
                 'style04_pink':           "Pink Zappa Moustache",
                 'style04_red':            "Red Zappa Moustache",
                 'style05_blond':          "Blond Mutton Chops",
                 'style05_brown':          "Brown Mutton Chops",
                 'style05_dark-gray':      "Dark Gray Mutton Chops",
                 'style05_light-gray':     "Ligth Gray Mutton Chops",
                 'style05_pink':           "Pink Mutton Chops",
                 'style05_red':            "Red Mutton Chops",
                 'style06_blond':          "Blond Soul Patch",
                 'style06_brown':          "Brown Soul Patch",
                 'style06_dark-gray':      "Dark Gray Soul Patch",
                 'style06_light-gray':     "Light Gray Soul Patch",
                 'style06_pink':           "Pink Soul Patch",
                 'style06_red':            "Red Soul Patch",
                 'style07_blond':          "Blond Full Goatee",
                 'style07_brown':          "Brown Full Goatee",
                 'style07_dark-gray':      "Dark Gray Full Goatee",
                 'style07_light-gray':     "Light Gray Full Goatee",
                 'style07_pink':           "Pink Full Goatee",
                 'style07_red':            "Red Full Goatee",
                 'style08_blond':          "Blond Moustache",
                 'style08_brown':          "Brown Moustache",
                 'style08_dark-gray':      "Dark Gray Moustache",
                 'style08_light-gray':     "Light Gray Moustache",
                 'style08_pink':           "Pink Moustache",
                 'style08_red':            "Red Moustache",
                 'style09_blond':          "Blond Full Beard",
                 'style09_brown':          "Brown Full Beard",
                 'style09_dark-gray':      "Dark Gray Full Beard",
                 'style09_light-gray':     "Light Gray Full Beard",
                 'style09_pink':           "Pink Full Beard",
                 'style09_red':            "Red Full Beard",
                 'style10_blond':          "Blond Thick Moustache",
                 'style10_brown':          "Brown Thick Moustache",
                 'style10_dark-gray':      "Dark Gray Thick Moustache",
                 'style10_light-gray':     "Light Gray Thick Moustache",
                 'style10_pink':           "Pink Thick Moustache",
                 'style10_red':            "Red Thick Moustache",
                 'style11':                "Stubble Beard"}, 
    'bowtie':   {'none':                   'none', 
                 'style01':                "Green Bowtie", 
                 'style02':                "Blue Bowtie", 
                 'style03':                "Yellow Bowtie", 
                 'style04':                "Red Bowtie"}, 
    'jacket': 
                {'none':                   'none', 
                 'style01':                "Gray Jacket - Black Sleeves", 
                 'style02':                "Red Jacket - White Sleeves", 
                 'style03':                "Black Jacket - Yellow Sleeves", 
                 'style04':                "Blue Polygon Jacket", 
                 'style05':                "Blue Stripes Jacket", 
                 'style06':                "Red Jacket", 
                 'style07':                "Black Jacket"}, 
    'torso':    {'none':                   'none',
                 'style01':                "Apron Shirt", 
                 'style02':                "Green Hawaiian Shirt", 
                 'style03':                "Red Hawaiian Shirt", 
                 'style04':                "Blue Hawaiian Shirt", 
                 'style05':                "Blue Shirt - Black Sleeves", 
                 'style06':                "Black & Red Shirt", 
                 'style07':                "Black & Yellow Shirt", 
                 'style08':                "Blue Polo Shirt", 
                 'style09':                "White Polo Shirt", 
                 'style10':                "Yellow Shirt - Blue Sleeves", 
                 'style11':                "Pink & White Wave Shirt", 
                 'style12':                "Gray & Yellow Wave Shirt", 
                 'style13':                "Round Blue Shirt", 
                 'style14':                "Round Purple Shirt", 
                 'style15':                "Round Green Shirt", 
                 'style16':                "Pink Shirt", 
                 'style17':                "Gray Shirt", 
                 'style18':                "Green Shirt", 
                 'style19':                "Blue Shirt", 
                 'style20':                "Red Shirt", 
                 'style21':                "Pink Skull Shirt", 
                 'style22':                "Black Skull Shirt", 
                 'style23':                "Yellow & Black Windbreaker", 
                 'style24':                "Pink & White Stripes Sweater", 
                 'style25':                "Gray & Blue Stripes Sweater", 
                 'style26':                "Green & Yellow Stripes Sweater", 
                 'style27':                "Blue & Blue Stripes Sweater", 
                 'style28':                "Brown & Gray Stripes Sweater",
                 'style29':                "Pink Sweater", 
                 'style30':                "Gray Sweater", 
                 'style31':                "Green Sweater", 
                 'style32':                "Blue Sweater", 
                 'style33':                "Brown Sweater", 
                 'style34':                "Blue Stripes Overalls", 
                 'style35':                "Yellow Overalls", 
                 'style36':                "Blue Overalls", 
                 'style37':                "Green Tracksuit", 
                 'style38':                "Gray Tracksuit", 
                 'style39':                "Red Tracksuit", 
                 'style40':                "Red Robe", 
                 'style41':                "Black Vest", 
                 'style42':                "Caramel Vest", 
                 'style43':                "Red Vest", 
                 'style44':                "Green Vest", 
                 'style45':                "Gray Vest"}, 
    'legs':     {'none':                   'none',
                 'style01':                "Red Pants", 
                 'style02':                "Blue Polygon Pants", 
                 'style03':                "Black Pants", 
                 'style04':                "Gray Pants", 
                 'style05':                "Blue Pants", 
                 'style06':                "Green Pants", 
                 'style07':                "White Pants", 
                 'style08':                "Lime Pants", 
                 'style09':                "Purple Pants", 
                 'style10':                "Pink Pants", 
                 'style11':                "Yellow Pants", 
                 'style12':                "Blue & Black Shorts", 
                 'style13':                "Red Shorts", 
                 'style14':                "Gray Shorts", 
                 'style15':                "Blue Shorts", 
                 'style16':                "Green Shorts", 
                 'style17':                "White Shorts", 
                 'style18':                "Lime Shorts", 
                 'style19':                "Purple Shorts", 
                 'style20':                "Pink Shorts", 
                 'style21':                "Yellow Shorts"}, 
    'shoes':    {'none':                   'none',
                 'style01':                "Red Boots", 
                 'style02':                "White Boots", 
                 'style03':                "Purple Boots", 
                 'style04':                "Green Boots", 
                 'style05':                "Pink Boots", 
                 'style06':                "Blue Boots", 
                 'style07':                "Brown Boots", 
                 'style08':                "Black & Gray Boots", 
                 'style09':                "Black Boots", 
                 'style10':                "White Cowboy Boots", 
                 'style11':                "Pink Cowboy Boots", 
                 'style12':                "Red Cowboy Boots", 
                 'style13':                "Green Cowboy Boots", 
                 'style14':                "Brown Cowboy Boots", 
                 'style15':                "Black Flip-Flops", 
                 'style16':                "White Flip-Flops", 
                 'style17':                "Brown Flip-Flops", 
                 'style18':                "Red Flip-Flops", 
                 'style19':                "Orange Slippers", 
                 'style20':                "Blue Slippers", 
                 'style21':                "Pink Slippers"},
    'skin':     {'none':                   'none',
                 'style01':                "Pink Rose", 
                 'style02':                "Sage Green", 
                 'style03':                "Pale Sky Blue", 
                 'style04':                "Rose Gold", 
                 'style05':                "Rosy Brown",
                 'style06':                "Dark Taupe"}
}

girl_styles_display = {
    'costume':  {'none':                   "none",
                 'style01':                "Polygon Astronaut Costume",
                 'style02':                "Sloth Costume", 
                 'style03':                "Panda Costume", 
                 'style04':                "Polar Bear Costume", 
                 'style05':                "Brown Bear Costume", 
                 'style06':                "Chicken Costume", 
                 'style07':                "Snake Costume", 
                 'style08':                "Gray Cat Costume", 
                 'style09':                "Orange Cat Costume", 
                 'style10':                "Black Cat Costume", 
                 'style11':                "Calico Cat Costume", 
                 'style12':                "Pug Costume", 
                 'style13':                "Monkey Costume", 
                 'style14':                "Crocodile Costume", 
                 'style15':                "Brown Bull Costume", 
                 'style16':                "Black Bull Costume", 
                 'style17':                "Alien Costume", 
                 'style18':                "Corgi Costume", 
                 'style19':                "Owl Costume", 
                 'style20':                "Frog Costume",
                 'style21':                "Red Panda Costume", 
                 'style22':                "Cow Costume", 
                 'style23':                "Pit Bull Costume", 
                 'style24':                "Tiger Costume", 
                 'style25':                "Dinosaur Costume", 
                 'style26':                "Penguin Costume",
                 'style27':                "Lion Costume",
                 'style28':                "Pig Costume",
                 'style29':                "Koala Costume",
                 'style30':                "Shark Costume"},
    'hat':      {'none':                   "none", 
                 'style01':                "Pink Conductor's Hat", 
                 'style02':                "Chef's Hat", 
                 'style03':                "Cowboy Hat", 
                 'style04':                "Penguin Hat", 
                 'style05':                "Dog Hat", 
                 'style06':                "Witch Hat", 
                 'style07':                "Red Stripes Cap", 
                 'style08':                "Red Cap", 
                 'style09':                "Fire Cap", 
                 'style10':                "Duck Cap", 
                 'style11':                "Viking Helmet", 
                 'style12':                "Policeman Cap", 
                 'style13':                "Boat Captain Hat", 
                 'style14':                "Gray Coonskin Hat", 
                 'style15':                "White Coonskin Hat", 
                 'style16':                "White Floppy Hat", 
                 'style17':                "Yellow Sun Hat", 
                 'style18':                "Gray Ushanka", 
                 'style19':                "Little Brown Bowler Hat", 
                 'style20':                "Blue Newsboy Hat", 
                 'style21':                "Green Bandana", 
                 'style22':                "Blue Bandana", 
                 'style23':                "Purple Bandana", 
                 'style24':                "Red Bandana", 
                 'style25':                "Blue Beanie", 
                 'style26':                "Green Beanie", 
                 'style27':                "Yellow Beanie", 
                 'style28':                "Purple Beanie",
                 'style29':                "Blue Heart Headband",
                 'style30':                "Red Heart Headband",
                 'style31':                "Red Bow Headband",
                 'style32':                "Blue Bow Headband"},
    'hair':     {'none':                   "none",
                 'style01_blond':          "Blond Chanel Hair",
                 'style01_brown':          "Brown Chanel Hair",
                 'style01_dark-gray':      "Dark Gray Chanel Hair",
                 'style01_light-gray':     "Light Gray Chanel Hair",
                 'style01_pink':           "Pink Chanel Hair",
                 'style01_red':            "Red Chanel Hair",
                 'style02_blond':          "Blond Long Hair",
                 'style02_brown':          "Brown Long Hair",
                 'style02_dark-gray':      "Dark Gray Long Hair",
                 'style02_light-gray':     "Light Gray Long Hair",
                 'style02_pink':           "Pink Long Hair",
                 'style02_red':            "Red Long Hair",
                 'style03_blond':          "Blond Afro Hair",
                 'style03_brown':          "Brown Afro Hair",
                 'style03_dark-gray':      "Dark Gray Afro Hair",
                 'style03_light-gray':     "Light Gray Afro Hair",
                 'style03_pink':           "Pink Afro Hair",
                 'style03_red':            "Red Afro Hair",
                 'style04_blond':          "Blond Medium Shag Hair",
                 'style04_brown':          "Brown Medium Shag Hair",
                 'style04_dark-gray':      "Dark Gray Medium Shag Hair",
                 'style04_light-gray':     "Light Gray Medium Shag Hair",
                 'style04_pink':           "Pink Medium Shag Hair",
                 'style04_red':            "Red Medium Shag Hair",
                 'style05_blond':          "Blond Side Shaved Hair",
                 'style05_brown':          "Brown Side Shaved Hair",
                 'style05_dark-gray':      "Dark Gray Side Shaved Hair",
                 'style05_light-gray':     "Light Gray Side Shaved Hair",
                 'style05_pink':           "Pink Side Shaved Hair",
                 'style05_red':            "Red Side Shaved Hair",
                 'style06_blond':          "Blond Curly Short Hair",
                 'style06_brown':          "Brown Curly Short Hair",
                 'style06_dark-gray':      "Dark Gray Curly Short Hair",
                 'style06_light-gray':     "Light Gray Curly Short Hair",
                 'style06_pink':           "Pink Curly Short Hair",
                 'style06_red':            "Red Curly Short Hair",
                 'style07_blond':          "Blond Ponytail Hair",
                 'style07_brown':          "Brown Ponytail Hair",
                 'style07_dark-gray':      "Dark Gray Ponytail Hair",
                 'style07_light-gray':     "Light Gray Ponytail Hair",
                 'style07_pink':           "Pink Ponytail Hair",
                 'style07_red':            "Red Ponytail Hair",
                 'style08_blond':          "Blond Sweeping Pixie Hair",
                 'style08_brown':          "Brown Sweeping Pixie Hair",
                 'style08_dark-gray':      "Dark Gray Sweeping Pixie Hair",
                 'style08_light-gray':     "Light Gray Sweeping Pixie Hair",
                 'style08_pink':           "Pink Sweeping Pixie Hair",
                 'style08_red':            "Red Sweeping Pixie Hair"},
    'glasses':  {'none':                   "none",
                 'style01':                "Modern Glasses", 
                 'style02':                "Big Frame Blue Glasses", 
                 'style03':                "Big Frame Green Glasses", 
                 'style04':                "Big Frame Red Glasses", 
                 'style05':                "Yellow Aviator Glasses", 
                 'style06':                "Teal Aviator Glasses", 
                 'style07':                "Gray Aviator Glasses", 
                 'style08':                "Purple Aviator Glasses", 
                 'style09':                "Full-Rimmed Glasses", 
                 'style10':                "Semi-Rimless Glasses", 
                 'style11':                "Small Teashade Sunglasses", 
                 'style12':                "Red Teashade Sunglasses", 
                 'style13':                "Old 3D Glasses", 
                 'style14':                "Black Sunglasses", 
                 'style15':                "Monocle",
                 'style16':                "White Framed Sunglasses",
                 'style17':                "Red Framed Sunglasses",
                 'style18':                "Big Blue Circular Glasses"}, 
    'eyes':     {'none':                   "none",
                 'style01':                "Red Eyes", 
                 'style02':                "Pink Eyes", 
                 'style03':                "Green Eyes", 
                 'style04':                "Blue Eyes", 
                 'style05':                "Black Eyes"}, 
    'nose':     {'none':                   "none",
                 'style01':                "Small Nose", 
                 'style02':                "Medium Nose", 
                 'style03':                "Big Nose"}, 
    'beard':    {'none':                   "none"}, 
    'bowtie':   {'none':                   "none"}, 
    'jacket':   {'none':                   "none", 
                 'style01':                "Big Black Jacket", 
                 'style02':                "Big Green Jacket", 
                 'style03':                "Big Brown Jacket", 
                 'style04':                "Big Teal Jacket", 
                 'style05':                "Big Pink Jacket", 
                 'style06':                "Small Blue Jacket", 
                 'style07':                "Small Dark Teal Jacket", 
                 'style08':                "Small Black Jacket", 
                 'style09':                "Small Yellow Jacket - Black Sleeves", 
                 'style10':                "Small Pink Jacket", 
                 'style11':                "Black Jacket - Pink Sleeves", 
                 'style12':                "Gray Jacket - Black Sleeves", 
                 'style13':                "Red Jacket - White Sleeves", 
                 'style14':                "Black Jacket - Yellow Sleeves", 
                 'style15':                "Blue Polygon Jacket", 
                 'style16':                "Blue Stripes Jacket", 
                 'style17':                "Red Jacket", 
                 'style18':                "Black Jacket"}, 
    'torso':    {'none':                   "none",
                 'style01':                "Apron Shirt", 
                 'style02':                "Green Hawaiian Shirt", 
                 'style03':                "Red Hawaiian Shirt", 
                 'style04':                "Blue Hawaiian Shirt", 
                 'style05':                "Green Summer Shirt", 
                 'style06':                "Baby Blue Summer Shirt", 
                 'style07':                "White Summer Shirt", 
                 'style08':                "Blue Polo Shirt", 
                 'style09':                "White Polo Shirt", 
                 'style10':                "Yellow Shirt - Blue Sleeves", 
                 'style11':                "Pink & White Wave Shirt", 
                 'style12':                "Gray & Yellow Wave Shirt", 
                 'style13':                "Round Blue Shirt", 
                 'style14':                "Round Purple Shirt", 
                 'style15':                "Round Green Shirt", 
                 'style16':                "Pink Shirt", 
                 'style17':                "Gray Shirt", 
                 'style18':                "Green Shirt", 
                 'style19':                "Blue Shirt", 
                 'style20':                "Red Shirt", 
                 'style21':                "Pink Skull Shirt", 
                 'style22':                "Black Skull Shirt", 
                 'style23':                "Gray & White Shirt", 
                 'style24':                "Pink Stripes Overalls", 
                 'style25':                "Yellow Overalls", 
                 'style26':                "Blue Overalls", 
                 'style27':                "Green Overalls", 
                 'style28':                "Green Tracksuit",
                 'style29':                "Gray Tracksuit", 
                 'style30':                "Red Tracksuit", 
                 'style31':                "Red Robe", 
                 'style32':                "Purple Strapless Dress", 
                 'style33':                "Blue Strapless Dress", 
                 'style34':                "Yellow Strapless Dress", 
                 'style35':                "Red Strapless Dress", 
                 'style36':                "Gray Strapless Dress", 
                 'style37':                "Green Strapless Dress", 
                 'style38':                "Pink Strapless Dress", 
                 'style39':                "Black Strapless Dress", 
                 'style40':                "Green Sundress", 
                 'style41':                "Black Sundress", 
                 'style42':                "Red Sundress", 
                 'style43':                "Pink Sundress", 
                 'style44':                "Yellow Sundress", 
                 'style45':                "Black Vest", 
                 'style46':                "Caramel Vest", 
                 'style47':                "Red Vest", 
                 'style48':                "Green Vest", 
                 'style49':                "Gray Vest", 
                 'style50':                "Yellow & Black Windbreaker", 
                 'style51':                "Pink & White Stripes Sweater", 
                 'style52':                "Gray & Blue Stripes Sweater", 
                 'style53':                "Green & Yellow Stripes Sweater", 
                 'style54':                "Blue & Blue Stripes Sweater", 
                 'style55':                "Brown & Gray Stripes Sweater", 
                 'style56':                "Pink Sweater", 
                 'style57':                "Gray Sweater", 
                 'style58':                "Green Sweater", 
                 'style59':                "Blue Sweater", 
                 'style60':                "Brown Sweater", 
                 'style61':                "Light Gray Sweater", 
                 'style62':                "Orange Sweater", 
                 'style63':                "Yellow Sweater", 
                 'style64':                "Fancy Gray Coat"}, 
    'legs':     {'none':                   "none",
                 'style01':                "Red Pants", 
                 'style02':                "Blue Polygon Pants", 
                 'style03':                "Black Pants", 
                 'style04':                "Gray Pants", 
                 'style05':                "Blue Pants", 
                 'style06':                "Green Pants", 
                 'style07':                "White Pants", 
                 'style08':                "Lime Pants", 
                 'style09':                "Purple Pants", 
                 'style10':                "Pink Pants", 
                 'style11':                "Yellow Pants", 
                 'style12':                "Pink & Black Skirt", 
                 'style13':                "Pink Skirt", 
                 'style14':                "White Skirt", 
                 'style15':                "Blue Skirt", 
                 'style16':                "Red Shorts", 
                 'style17':                "Gray Shorts", 
                 'style18':                "Blue Shorts", 
                 'style19':                "Green Shorts", 
                 'style20':                "White Shorts", 
                 'style21':                "Lime Shorts",
                 'style22':                "Purple Shorts",
                 'style23':                "Pink Shorts",
                 'style24':                "Yellow Shorts"}, 
    'shoes':    {'none':                   "none",
                 'style01':                "Black Flip-Flops", 
                 'style02':                "White Flip-Flops", 
                 'style03':                "Brown Flip-Flops", 
                 'style04':                "Red Flip-Flops", 
                 'style05':                "Red Boots", 
                 'style06':                "White Boots", 
                 'style07':                "Purple Boots", 
                 'style08':                "Green Boots", 
                 'style09':                "Pink Boots", 
                 'style10':                "Blue Boots", 
                 'style11':                "Brown Boots", 
                 'style12':                "Black & Gray Boots", 
                 'style13':                "Black Boots", 
                 'style14':                "Orange Slippers", 
                 'style15':                "Blue Slippers", 
                 'style16':                "Pink Slippers", 
                 'style17':                "Purple Shoes", 
                 'style18':                "Teal Shoes", 
                 'style19':                "Blue Shoes", 
                 'style20':                "Black Shoes", 
                 'style21':                "Salmon Shoes",
                 'style22':                "Pink Shoes",
                 'style23':                "Marigold Shoes",
                 'style24':                "Royal Blue Shoes"},
    'skin':     {'none':                   "none",
                 'style01':                "Pink Rose", 
                 'style02':                "Sage Green", 
                 'style03':                "Pale Sky Blue", 
                 'style04':                "Rose Gold", 
                 'style05':                "Rosy Brown",
                 'style06':                "Dark Taupe"}
}

